# https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions
name: 'Star Helper'
description: 'A GitHub Action help you star or unstar a repository.'
author: 'xrkffgg'

# https://actions-cool.github.io/github-action-branding/
branding:
  icon: 'star'
  color: 'yellow'

inputs:
  token:
    description: Secret GitHub API token to use for making API requests.
    required: true
  repo:
    description: The repository name.
  actions:
    description: The Actions. Options `star` `unstar`.
    required: true

outputs:
  star-count:
    description: Return the repository star count after actions.

runs:
  using: 'node12'
  main: 'dist/index.js'
